import data
from stringcolor import * 
import time
import random
from steps import sheep

for x in range(0, 1000):
	print("")

print ("Welcome to "+cs("A", "red2") +cs("n", "orangered") +cs(" R", "yellow3") +cs("P", "green") +cs("G", "skyblue") +cs("!", "violet"))
time.sleep(1.5)
print("")
print ("Here in "+cs("A", "red2") +cs("n", "orangered") +cs(" R", "yellow3") +cs("P", "green") +cs("G", "skyblue") +cs(", You'll explore a vast land filled with wonder and mystery!", "white"))
time.sleep(2.75)
print("")
print("Here are your stats:")
data.stats()
time.sleep(2.5)
print("")
print("You probably don't know what these mean, however you will later.")
time.sleep(2.5)
print("")
print("Let's go somewhere else shall we?")
time.sleep(2.5)

for x in range(0, 1000):
	print("")

time.sleep(1)
print("This place feels much better.")
time.sleep(1.59)
print("")
input("Press enter to continue,")
print("")
input("You'll have to do this a lot.")
print("")
input("Anyways, I'll explain your stats,")
print("")
input("First, Max HP, this is how much your health can go to.")
print("")
input("Second, Attack, this is how much damage physical attacks do.")
print("")
input("Third, Magic, this is how much damage magical attacks do.")
print("")
input("Finally, Luck, this is your chance of hitting a critical hit.")
print("")
input("Now that you're all caught up, let's go on an adventure")

data.resc()
input("Take a step by pressing enter.")
data.step()
input("Take another one,")
data.step()
input("Another,")
data.step()
input("Another,")
data.step()
input("Great!") 
data.step()
thing = input("Now to access the shop, write 'shop' (no caps) and click enter. ")
if thing == "shop":
	data.shop()
	data.resc()
	input("Great! Now continue.")
else:
	print("You have failed the game, sorry.")
	exit()
data.step()
print("Now, here are your stats, (The stick increased your attack.)")
data.stats()
print("")
input("Weird right?")
data.step()
input("Ah! It's a monster! Fight it!")
data.combat()
input("Phew.")
data.step()
name = input("Now what is your name? ")
data.step()
input(f"That's great, {name}")
data.step()
input(f"Before I send you off {name}, you can write 'shop' to get to the shop, and 'stats' to see your stats.")
data.step()
input("Alright, bye!")
data.tutorial = False
for x in range (0, 1000):
	data.step()
	sheep()
data.resc()
print("You have reached the end of the game (for now), I'm working on more content for the future! Bye!")